name: Build Executables

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  linux:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: |
          yarn install
          yarn make
      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: linux-exec
          path: out/
  win:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - name: Install deps and package
        run: |
          yarn install
          yarn make
      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: win-exec
          path: out/

  mac:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 15.x
      - run: |
          yarn install
          yarn make
      - name: Upload Executable
        uses: actions/upload-artifact@v2
        with:
          name: mac-exec
          path: out/
